environment:
  matrix:
    # We only test on one Python version as builds are slow.
    - PYTHON_VERSION: "3.7"

init:
  - cmd: SET PYTHON=C:\\Miniconda37-x64
  - cmd: ECHO Using %PYTHON%

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda create --yes -n testenv python=%PYTHON_VERSION%
  - cmd: activate testenv
  - cmd: conda install --yes --file=requirements\conda-minimal.txt
  - cmd: conda info -a
  - cmd: python --version
  # daiquiri isn't available on conda-forge. This will be a problem when 
  # building our own packages, so we either need to package daiquiri or 
  # remove the dependency.
  - cmd: python -m pip install daiquiri

build_script:
  - cmd: python -m nose -vs

after_test:
  - cmd: python setup.py bdist_wheel
