version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: /home/circleci/stdpopsim
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci *
      - restore_cache:
          key: stdpopsim-{{ .Branch }}
      - run:
          name: Install dependencies and set path
          command: |
            sudo apt-get install libgsl-dev # Needed for msprime
            pip install --user -r requirements/development.txt
            pip install twine --user
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Build and install SLiM
          command: |
            sudo apt-get install cmake
            wget http://benhaller.com/slim/SLiM.zip
            unzip SLiM.zip
            mkdir SLiM/build
            cd SLiM/build && cmake .. && make
            cp slim /home/circleci/.local/bin/
      - save_cache:
          key: stdpopsim-{{ .Branch }}
          paths:
            - "/home/circleci/.local"

      - run:
          name: Lint Python
          command: |
            flake8 --version
            flake8 --max-line-length 89 stdpopsim setup.py tests docs/_ext

      - run:
          name: Run Python tests
          command: |
            nosetests -vs --with-coverage --cover-package stdpopsim maintenance \
              --cover-branches --cover-erase --cover-xml \
              --cover-inclusive tests
            python3 -m codecov
            rm .coverage

      - run:
          name: Build Python package
          command: |
            rm -fR build
            python setup.py sdist
            python setup.py check
            python -m twine check dist/*.tar.gz
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade setuptools pip wheel
            python setup.py build_ext
            python setup.py egg_info
            python setup.py bdist_wheel
            pip install dist/*.tar.gz
            python3 -m stdpopsim -V
            # Run a small simulation to make sure it all works.
            stdpopsim HomSap -c chr22 -l 0.001 2 > /dev/null

      - run:
          name: Build docs
          command: |
            source venv/bin/activate
            cd docs && make && make singlehtml
