name: stdpopsim-rtd

channels:
  - conda-forge
  - bioconda

dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - gsl=2.6
  - libblas=3.8.0
  - libcblas=3.8.0
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libopenblas=0.3.9
  - llvm-openmp=10.0.0
  - python=3.8
  - sphinx-argparse=0.2.5
  - sphinx-issues=1.2.0
  - sphinxcontrib-programoutput=0.16
  - scipy
